---
collections:
  - name: lit.foundational
    version: "1.15.0"
  - name: lit.rhel
    version: "1.9.3"
  - name: lit.supplementary
    version: "1.16.5"
  - name: lit.ocp
    version: "1.3.3"
  # renovate: datasource=github-tags depName=ansible/ansible.platform
  - name: https://github.com/ansible/ansible.platform.git
    type: git
    version: "2.6.20251106"
  - name: ansible.posix
    version: "2.1.0"
  - name: ansible.hub
    version: "1.0.4"
  - name: ansible.eda
    version: "2.11.0"
  - name: infra.aap_utilities
    version: "2.8.0"
  - name: infra.aap_configuration
    version: "4.2.1"
  - name: infra.aap_configuration_extended
    version: "4.2.1"
  - name: infra.controller_configuration
    version: "3.2.2"
  - name: infra.ee_utilities
    version: "4.2.2"
  - name: community.general
    version: "11.4.4"
  - name: community.crypto
    version: "3.1.1"
  - name: community.hashi_vault
    version: "7.1.0"
  - name: community.vmware
    version: "5.10.0"
  - name: containers.podman
    version: "1.19.0"
  - name: fedora.linux_system_roles
    version: "1.120.3"
