---
collections:
  - name: ansible.platform
    version: "2.5.20250702"
  - name: lit.foundational
    version: "1.15.0"
  - name: lit.rhel
    version: "1.9.2"
  - name: lit.supplementary
    version: "1.15.1"
  - name: lit.ocp
    version: "1.3.2"
